### ISSUE TITLE
Tortendiagramm

### ISSUE THREAD

**Issue by StrikerCatSharky** [JosiNeust/Projekt#2]
@cziegl Was hältst du von der Idee, die grafische Umsetzung der Aufgabe in einem Tortendiagramm zu verwirklichen? Hier ließe sich gut darstellen, welchen prozentualen Anteil jede der von IMDb bereits vordefinierten Titelarten jeweils einnimmt. Außerdem hätten wir dann noch eine sich von den anderen unterscheidende Diagrammform.

**Comment by cziegl** [comment]
@StrikerCatSharky klar kann ich gerne machen
